openapi: 3.0.0
info:
  version: 1.0.0
  title: Goala API
  description: First iteration of Goala API documentation

paths:
# Authentication
  /auth/register:
    $ref: './paths/auth/register.yml'
  /auth/login:
    $ref: './paths/auth/login.yml'

# User operations
  /users/me:
    $ref: './paths/users/me.yml'
  /users/id/{userId}:
    $ref: './paths/users/users.yml'

  # Exercise endpoint
  /exercises:
    $ref: './paths/exercises/exercises.yml'
      
  # Workout endpoint
  /workouts:
    $ref: './paths/workouts/workouts.yml'
  # Add exercise to workout
  /workouts/id/{workout_id}:
    $ref: './paths/workouts/add-exercise-to-workout.yml'
  # Get workout exercises
  /workouts/id/{workout_id}/exercises:
    $ref: './paths/workouts/get-workout-exercises.yml'
  # Remove exercise from workout
  /workouts/id/{workout_id}/exercises/{exercise_id}:
    $ref: './paths/workouts/remove-exercise-from-workout.yml'