openapi: 3.0.0
info:
  version: 1.0.0
  title: Goala API
  description: First iteration of Goala API documentation

paths:
# Authentication
  /auth/register:
    $ref: './paths/auth/register.yml'
  /auth/login:
    $ref: './paths/auth/login.yml'

# User operations
  /users/me:
    $ref: './paths/users/me.yml'
  /users/id/{userId}:
    $ref: './paths/users/users.yml'

  # Exercise endpoint
  /exercises:
    $ref: './paths/exercises/exercises.yml'
  /exercises/{bodypart}:
    get:
      tags:
        - Exercises
      summary: Get exercises for specific bodypart
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      exercises:
                        type: array
                        items:
                            $ref: '#/components/schemas/Exercise'
        '400':
          description: Unknown bodypart
        '500':
          description: General Server Error
      
  # Workout endpoint
  /workouts:
    $ref: './paths/exercises/exercises.yml'