openapi: 3.0.0
info:
  version: 1.0.0
  title: Goala API
  description: First iteration of Goala API documentation

paths:
# Authentication
  /auth/register:
    $ref: './paths/auth/register.yml'
  /auth/login:
    $ref: './paths/auth/login.yml'

# User operations
  /users/me:
    $ref: './paths/users/me.yml'
  /users/id/{userId}:
    $ref: './paths/users/users.yml'
  /users/logout:
    $ref: './paths/users/logout.yml'

  # Exercise endpoint
  /exercises:
    $ref: './paths/exercises/exercises.yml'
      
  # Workout endpoint
  /workouts:
    $ref: './paths/exercises/exercises.yml'

  # Files endpoint 
  /files:
    $ref: './paths/files/files.yml'

  /refresh-token:
    $ref: './paths/refresh-token/refresh-token.yml'