openapi: 3.0.0
info:
  version: 1.0.0
  title: Goala API
  description: First iteration of Goala API documentation
components:
  schemas:
    User:
      type: object
      properties:
        user_name:
          type: string
        email:
          type: string
        mobile:
          type: number
        date_of_birth:
          type: string
          format: date
    updatedData:
      type: object
      properties:
        updatedData:
          $ref: "#/components/schemas/User"
    Bodypart:
      type: string
      enum:
        - chest
        - shoulders
        - biceps
        - triceps
        - forearms
        - back
        - hamstrings
        - quads
        - calves
        - abs
        - glutes
        - abductors
        - adductors
    Privacy:
      type: string
      enum:
        - public
        - private
        
    Exercise:
      type: object
      properties:
        exercise_id:
          type: string
          format: uuid
        name:
          type: string
        bodypart_primary:
          $ref: '#/components/schemas/Bodypart'
        bodypart_secondary:
          $ref: '#/components/schemas/Bodypart'
        description:
          type: string
    Workout:
      type: object
      properties:
        workout_id:
          type: string
          format: uuid
        workout_name:
          type: string
        description:
          type: string
        creator:
          type: string
          format: uuid
        privacy: 
          $ref: '#/components/schemas/Privacy'
        is_promoted:
          type: boolean

paths:
# Authentication
  /auth/register:
    post:
      tags: 
        - Authentication
      summary: Register a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                user_name:
                  type: string
                password:
                  type: string
                mobile:
                  type: number
                date_of_birth:
                  type: string
                  format: date
              required: 
                - email
                - user_name
                - password
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad Request
        '409':
          description: User already exists
        '500':
          description: General Server Error
  /auth/login:
    post:
      tags: 
        - Authentication
      summary: Login an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: Username or email
                password:
                  type: string
              required: 
                - login
                - password
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400': 
          description: Bad Request
        '401':
          description: Authentication failed
        '500':
          description: General Server Error
        
# User operations
  /user/me:
    get:
      tags:
        - User 
      summary: Get current user
      description: Returns data for currently logged in user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: No authenticated user
        '500':
          description: General server error
  /user/id/{userId}:
    delete:
      tags:
        - User
      summary: Delete a user by id
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: Id of user to be deleted
      responses:
        '200': 
          description: OK
        '404':
          description: User with given ID does not exist
        '500':
          description: General Server Error
    patch:
      tags:
        - User
      summary: Update User
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: Id of user to be updated
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatedData'  
            example:
              updatedData: { user_name: 'foo' }
      responses:
        '200': 
          description: OK
        '404':
          description: User with given ID does not exist
        '500':
          description: General Server Error
    get:
      tags: 
        - User
      summary: Get profile for user given ID
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User with given ID does not exist
        '500':
          description: General Server Error

  # Exercise endpoint
  /exercise:
    get:
      tags:
        - Exercise
      summary: Get all exercises
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
        '500':
          description: General Server Error

  /exercise/{bodypart}:
    get:
      tags:
        - Exercise
      summary: Get exercises for specific bodypart
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
        '400':
          description: Unknown bodypart
        '500':
          description: General Server Error
      
  # Workout endpoint
  /workouts:
    get:
      tags:
        - Workouts
      parameters:
        - in: query
          name: user
          schema:
            type: string
            format: uuid
          description: returns workouts available to given user
        - in: query
          name: creator
          schema:
            type: string
            format: uuid
          description: Returns all workouts created by given creator
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '400':
          description: Profile does not exist
        '500':
          description: General Server Error
